/**
 * 演示数据集 · 单一事实源（批5 起 data/ 目录已删除）。
 *
 * 保持 JSON 文件时代的原始形状（含 _count、嵌套 version/agent 等演示字段），
 * 两个消费方：
 * - packages/db/prisma/seed.mjs —— 展平映射后写入 PostgreSQL（db:seed）
 * - apps/web/demo/seed.ts —— 浏览器演示模式（NEXT_PUBLIC_DEMO_MODE=1）的初始内存态
 */

export const users = [
  { id: "user-zhao", email: "admin-zhao@example.com", name: "赵管理员" },
  { id: "user-chen", email: "pm-chen@example.com", name: "陈产品" },
  { id: "user-wang", email: "cre-wang@example.com", name: "王客服" },
  { id: "user-zhang", email: "cre-zhang@example.com", name: "张客服" },
  { id: "user-li", email: "eng-li@example.com", name: "李工程师" },
  { id: "user-liu", email: "cre-li@example.com", name: "刘客服" },
];

export const permissions = [
  { id: "perm-1", resource: "agent", action: "read", description: "查看 Agent", _count: { roles: 3 } },
  { id: "perm-2", resource: "agent", action: "write", description: "编辑 Agent", _count: { roles: 2 } },
  { id: "perm-3", resource: "agent", action: "publish", description: "提交发布", _count: { roles: 2 } },
  { id: "perm-4", resource: "release", action: "approve", description: "审批发布", _count: { roles: 1 } },
  { id: "perm-5", resource: "settings", action: "admin", description: "管理设置", _count: { roles: 1 } },
  { id: "perm-6", resource: "feedback", action: "read", description: "查看反馈", _count: { roles: 3 } },
  { id: "perm-7", resource: "feedback", action: "write", description: "录入反馈", _count: { roles: 2 } },
  { id: "perm-8", resource: "wiki", action: "read", description: "查看知识库", _count: { roles: 3 } },
  { id: "perm-9", resource: "wiki", action: "write", description: "编辑知识库", _count: { roles: 2 } },
  { id: "perm-10", resource: "audit", action: "read", description: "查看审计日志", _count: { roles: 1 } },
];

export const roles = [
  {
    id: "role-admin",
    name: "platform_admin",
    displayName: "平台管理员",
    isSystem: true,
    description: "拥有所有权限",
    _count: { members: 1 },
    permissions: [
      { permission: { id: "perm-1", resource: "agent", action: "read" } },
      { permission: { id: "perm-2", resource: "agent", action: "write" } },
      { permission: { id: "perm-3", resource: "agent", action: "publish" } },
      { permission: { id: "perm-4", resource: "release", action: "approve" } },
      { permission: { id: "perm-5", resource: "settings", action: "admin" } },
    ],
  },
  {
    id: "role-product",
    name: "product_member",
    displayName: "产品组成员",
    isSystem: true,
    description: "可编辑本产品组的 Agent 配置",
    _count: { members: 5 },
    permissions: [
      { permission: { id: "perm-1", resource: "agent", action: "read" } },
      { permission: { id: "perm-2", resource: "agent", action: "write" } },
      { permission: { id: "perm-3", resource: "agent", action: "publish" } },
    ],
  },
  {
    id: "role-cre",
    name: "cre_viewer",
    displayName: "CRE 查看者",
    isSystem: true,
    description: "可查看反馈和提交改进建议",
    _count: { members: 8 },
    permissions: [
      { permission: { id: "perm-1", resource: "agent", action: "read" } },
    ],
  },
];

export const productGroups = [
  {
    id: "ecs-group",
    name: "ecs-group",
    displayName: "ECS 产品组",
    description: "ECS 云服务器产品线",
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-07-10T00:00:00.000Z",
    _count: { agents: 1, members: 3 },
  },
  {
    id: "rds-group",
    name: "rds-group",
    displayName: "RDS 产品组",
    description: "RDS 数据库产品线",
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-07-08T00:00:00.000Z",
    _count: { agents: 1, members: 2 },
  },
];

export const productGroupMembers = [
  { id: "pgm-1", productGroupId: "ecs-group", userId: "user-chen", role: "LEAD" },
  { id: "pgm-2", productGroupId: "ecs-group", userId: "user-wang", role: "MEMBER" },
  { id: "pgm-3", productGroupId: "ecs-group", userId: "user-zhang", role: "MEMBER" },
  { id: "pgm-4", productGroupId: "rds-group", userId: "user-li", role: "LEAD" },
  { id: "pgm-5", productGroupId: "rds-group", userId: "user-liu", role: "MEMBER" },
];

export const userRoles = [
  { id: "ur-1", userId: "user-zhao", roleId: "role-admin", assignedBy: "seed" },
  { id: "ur-2", userId: "user-chen", roleId: "role-product", assignedBy: "seed" },
  { id: "ur-3", userId: "user-li", roleId: "role-product", assignedBy: "seed" },
  { id: "ur-4", userId: "user-wang", roleId: "role-cre", assignedBy: "seed" },
  { id: "ur-5", userId: "user-zhang", roleId: "role-cre", assignedBy: "seed" },
  { id: "ur-6", userId: "user-liu", roleId: "role-cre", assignedBy: "seed" },
];

export const agents = [
  {
    id: "ecs-assistant",
    name: "ECS 工单助手",
    description: "处理 ECS 云服务器相关的工单咨询，包括实例管理、网络配置、磁盘扩容等",
    productGroupId: "ecs-group",
    status: "ACTIVE",
    createdAt: "2026-06-15T08:00:00.000Z",
    updatedAt: "2026-07-10T14:30:00.000Z",
    createdBy: "system",
    promptConfig: {
      systemPrompt: "你是一个专业的 ECS 云服务器技术支持助手。你的职责是帮助 CRE（客户可靠性工程师）快速定位和解决 ECS 相关工单问题。\n\n## 核心能力\n- ECS 实例管理（创建、启停、释放、变配）\n- 网络配置（VPC、安全组、弹性公网 IP）\n- 存储管理（云盘、快照、NAS 挂载）\n- 故障排查（实例无法连接、性能问题、系统异常）\n\n## 回答原则\n1. 先确认问题现象和环境信息\n2. 给出排查步骤和可能的解决方案\n3. 涉及高危操作时明确提示风险\n4. 不确定的问题建议联系 ECS 内核团队\n\n## 运行环境（MOCK）\n- 主模型：Qwen-Max（公共云经百炼 DashScope；专有云经 Apsara Stack 私有化推理）\n- 降级模型：Qwen-Plus；分类模型：Qwen-Turbo",
      roleDefinition: "ECS 技术支持专家",
      constraints: ["不回答非 ECS 产品的问题", "不执行任何实际变更操作", "涉及数据安全的问题提醒用户注意"],
      outputFormat: "Markdown",
    },
    knowledgeConfig: {
      wikiVaultId: "ecs-wiki",
      searchStrategy: "HYBRID",
      fallbackToMcp: true,
      maxWikiResults: 5,
      confidenceThreshold: 0.6,
    },
    toolsConfig: {
      mcpTools: [
        {
          name: "ecs_instance_query",
          displayName: "ECS 实例查询",
          description: "根据实例 ID 或条件查询 ECS 实例状态",
          endpoint: "https://ecs-api.internal/v1/instances",
          method: "GET",
          inputSchema: { type: "object", properties: { instanceId: { type: "string" } } },
          outputSchema: { type: "object" },
          authType: "bearer",
          permissionScope: "read_only",
          enabled: true,
        },
        {
          name: "bailian_kb_retrieval",
          displayName: "百炼知识库检索（MOCK）",
          description: "从百炼 RAG 知识库（公共云）/ 私有向量检索（专有云）检索工单处理知识",
          endpoint: "https://dashscope.aliyuncs.com/api/v1/mock/bailian-kb-retrieval",
          method: "POST",
          inputSchema: { type: "object", properties: { query: { type: "string" }, topK: { type: "number" } } },
          outputSchema: { type: "object" },
          authType: "bearer",
          permissionScope: "read_only",
          enabled: true,
        },
        {
          name: "dashscope_text_embedding",
          displayName: "DashScope 文本向量化（MOCK）",
          description: "text-embedding-v3 生成查询向量，供专有云私有向量检索使用",
          endpoint: "https://dashscope.aliyuncs.com/api/v1/services/embeddings/text-embedding/text-embedding",
          method: "POST",
          inputSchema: { type: "object", properties: { texts: { type: "array" } } },
          outputSchema: { type: "object" },
          authType: "bearer",
          permissionScope: "read_only",
          enabled: true,
        },
      ],
      wikiQueryTools: [
        {
          name: "wiki_search",
          displayName: "知识库搜索",
          description: "在 ECS 知识库中搜索相关知识",
          searchType: "hybrid",
          maxResults: 5,
          minConfidence: 0.6,
          enabled: true,
        },
        {
          name: "bailian_rag_fallback",
          displayName: "百炼 RAG 兜底检索（MOCK）",
          description: "wiki 蒸馏知识未命中时回退百炼 RAG 原始检索",
          searchType: "vector",
          maxResults: 3,
          minConfidence: 0.5,
          enabled: true,
        },
      ],
      maxConcurrentCalls: 3,
      timeoutMs: 30000,
      retryCount: 2,
    },
    routingConfig: {
      rules: [
        {
          id: "rule-1",
          name: "实例无法连接",
          matchCondition: { keywords: ["无法连接", "SSH失败", "远程桌面", "网络不通"], category: "connectivity" },
          action: { type: "route_to_agent", targetAgentId: "ecs-assistant", priority: 1 },
        },
        {
          id: "rule-2",
          name: "性能问题",
          matchCondition: { keywords: ["CPU高", "内存不足", "磁盘满", "IO瓶颈"], category: "performance" },
          action: { type: "route_to_agent", targetAgentId: "ecs-assistant", priority: 2 },
        },
      ],
      defaultAction: { type: "route_to_human", reason: "未匹配到已知问题类型" },
      humanThreshold: 0.3,
      maxConversationTurns: 10,
      idleTimeoutMinutes: 5,
    },
    _count: { feedbacks: 3, releases: 2, versions: 2, skillBindings: 1 },
  },
  {
    id: "rds-assistant",
    name: "RDS 工单助手",
    description: "处理 RDS 数据库相关的工单咨询，包括连接问题、性能优化、备份恢复等",
    productGroupId: "rds-group",
    status: "ACTIVE",
    createdAt: "2026-06-20T08:00:00.000Z",
    updatedAt: "2026-07-08T10:00:00.000Z",
    createdBy: "system",
    promptConfig: {
      systemPrompt: "你是一个专业的 RDS 数据库技术支持助手。帮助 CRE 处理 MySQL、PostgreSQL、SQL Server 等数据库相关工单。\n\n## 核心能力\n- 数据库连接问题排查\n- 慢查询分析与优化建议\n- 备份恢复操作指导\n- 参数调优建议\n\n## 运行环境（MOCK）\n- 主模型：Qwen-Plus（公共云经百炼 DashScope；专有云经 Apsara Stack 私有化推理）\n- 降级模型：Qwen-Turbo；复杂慢查询分析升级 Qwen-Max",
      roleDefinition: "RDS 数据库技术支持专家",
      constraints: ["不执行 DDL/DML 操作", "涉及数据迁移时提醒备份", "不直接查看用户数据"],
      outputFormat: "Markdown",
    },
    knowledgeConfig: {
      wikiVaultId: "rds-wiki",
      searchStrategy: "WIKI_FIRST",
      fallbackToMcp: true,
      maxWikiResults: 5,
      confidenceThreshold: 0.6,
    },
    toolsConfig: {
      mcpTools: [
        {
          name: "bailian_kb_retrieval",
          displayName: "百炼知识库检索（MOCK）",
          description: "从百炼 RAG 知识库检索 RDS 排障与优化知识",
          endpoint: "https://dashscope.aliyuncs.com/api/v1/mock/bailian-kb-retrieval",
          method: "POST",
          inputSchema: { type: "object", properties: { query: { type: "string" }, topK: { type: "number" } } },
          outputSchema: { type: "object" },
          authType: "bearer",
          permissionScope: "read_only",
          enabled: true,
        },
        {
          name: "dashscope_text_embedding",
          displayName: "DashScope 文本向量化（MOCK）",
          description: "text-embedding-v3 生成查询向量，供私有向量检索使用",
          endpoint: "https://dashscope.aliyuncs.com/api/v1/services/embeddings/text-embedding/text-embedding",
          method: "POST",
          inputSchema: { type: "object", properties: { texts: { type: "array" } } },
          outputSchema: { type: "object" },
          authType: "bearer",
          permissionScope: "read_only",
          enabled: true,
        },
      ],
      wikiQueryTools: [],
      maxConcurrentCalls: 3,
      timeoutMs: 30000,
      retryCount: 2,
    },
    routingConfig: {
      rules: [],
      defaultAction: { type: "route_to_human", reason: "未匹配已知问题" },
      humanThreshold: 0.3,
      maxConversationTurns: 10,
      idleTimeoutMinutes: 5,
    },
    _count: { feedbacks: 1, releases: 1, versions: 1, skillBindings: 0 },
  },
];

export const wikiVaults = [
  {
    id: "ecs-wiki",
    name: "ECS 知识库",
    description: "ECS 云服务器相关知识，包括实例管理、网络、存储、故障排查等",
    agentId: "ecs-assistant",
    isShared: false,
    gitRepoUrl: null,
    gitBranch: "main",
    pageCount: 3,
    avgConfidence: 0.78,
    orphanCount: 0,
    createdAt: "2026-06-15T08:00:00.000Z",
    updatedAt: "2026-07-13T14:00:00.000Z",
    _count: { pages: 3, ingestJobs: 0 },
  },
  {
    id: "rds-wiki",
    name: "RDS 知识库",
    description: "RDS 数据库相关知识，包括连接、性能、备份恢复等",
    agentId: "rds-assistant",
    isShared: false,
    gitRepoUrl: null,
    gitBranch: "main",
    pageCount: 1,
    avgConfidence: 0.85,
    orphanCount: 0,
    createdAt: "2026-06-20T08:00:00.000Z",
    updatedAt: "2026-07-08T10:00:00.000Z",
    _count: { pages: 1, ingestJobs: 0 },
  },
];

export const wikiPages = [
  {
    id: "page-ecs-disk",
    vaultId: "ecs-wiki",
    title: "云盘扩容操作指南",
    slug: "disk-expansion",
    summary: "在线扩容和离线扩容的操作步骤及注意事项，包括扩容前创建快照的建议",
    provenance: "EXTRACTED",
    lifecycle: "REVIEWED",
    tier: "SUPPORTING",
    baseConfidence: 0.7,
    tags: ["云盘", "扩容", "存储"],
    categories: ["storage"],
    wikilinks: ["security-group-guide"],
    filePath: "storage/disk-expansion.md",
    updatedAt: "2026-07-12T10:00:00.000Z",
  },
  {
    id: "page-ecs-sg",
    vaultId: "ecs-wiki",
    title: "安全组配置指南",
    slug: "security-group-guide",
    summary: "ECS 安全组的入方向和出方向规则配置方法，包括常见端口放通场景",
    provenance: "EXTRACTED",
    lifecycle: "VERIFIED",
    tier: "CORE",
    baseConfidence: 0.9,
    tags: ["安全组", "网络", "端口"],
    categories: ["network"],
    wikilinks: ["vpc-basics", "elastic-ip"],
    filePath: "network/security-group-guide.md",
    updatedAt: "2026-07-13T14:00:00.000Z",
  },
  {
    id: "page-ecs-ssh",
    vaultId: "ecs-wiki",
    title: "SSH 连接故障排查",
    slug: "ssh-troubleshooting",
    summary: "SSH 无法连接 ECS 实例的完整排查流程：网络→安全组→SSH 服务→密钥验证",
    provenance: "EXTRACTED",
    lifecycle: "VERIFIED",
    tier: "CORE",
    baseConfidence: 0.95,
    tags: ["SSH", "故障排查", "连接"],
    categories: ["troubleshooting"],
    wikilinks: ["security-group-guide"],
    filePath: "troubleshooting/ssh-troubleshooting.md",
    updatedAt: "2026-07-10T11:00:00.000Z",
  },
  {
    id: "page-rds-conn",
    vaultId: "rds-wiki",
    title: "RDS 连接问题排查",
    slug: "connection-troubleshooting",
    summary: "MySQL/PostgreSQL 连接失败的排查步骤：白名单→账号密码→网络→连接数",
    provenance: "EXTRACTED",
    lifecycle: "VERIFIED",
    tier: "CORE",
    baseConfidence: 0.85,
    tags: ["连接", "排查", "白名单"],
    categories: ["troubleshooting"],
    wikilinks: [],
    filePath: "troubleshooting/connection-troubleshooting.md",
    updatedAt: "2026-07-08T10:00:00.000Z",
  },
];

export const skills = [
  {
    id: "skill-ticket-lookup",
    name: "ticket-lookup",
    displayName: "工单查询",
    description: "根据工单号查询工单详情、状态和处理历史",
    category: "DATA_FETCH",
    triggerPatterns: ["查工单", "工单号", "ticket"],
    inputSchema: { type: "object", properties: { ticketId: { type: "string" } } },
    outputSchema: { type: "object" },
    runtime: "HTTP",
    endpoint: "https://ticket-api.internal/v1/tickets",
    version: "2.0.0",
    status: "PUBLISHED",
    publishedAt: "2026-07-05T00:00:00.000Z",
    downloadCount: 8,
    authorId: "system",
    authorName: "Platform",
    createdAt: "2026-07-03T00:00:00.000Z",
    updatedAt: "2026-07-12T00:00:00.000Z",
    _count: { bindings: 1, versions: 2 },
  },
  {
    id: "skill-wiki-search",
    name: "wiki-search",
    displayName: "Wiki 知识库搜索",
    description: "在 Agent 关联的 Wiki 知识库中进行语义搜索，返回最相关的知识页面",
    category: "KNOWLEDGE_QUERY",
    triggerPatterns: ["搜索知识", "查一下", "知识库"],
    inputSchema: { type: "object", properties: { query: { type: "string" }, maxResults: { type: "number" } } },
    outputSchema: { type: "object", properties: { results: { type: "array" } } },
    runtime: "MCP",
    endpoint: null,
    version: "1.0.0",
    status: "PUBLISHED",
    publishedAt: "2026-07-01T00:00:00.000Z",
    downloadCount: 12,
    authorId: "system",
    authorName: "Platform",
    createdAt: "2026-07-01T00:00:00.000Z",
    updatedAt: "2026-07-10T00:00:00.000Z",
    _count: { bindings: 2, versions: 1 },
  },
];

export const skillVersions = [
  { skillId: "skill-ticket-lookup", version: "1.0.0", changelog: "初始版本", publishedAt: "2026-07-03T00:00:00.000Z" },
  { skillId: "skill-ticket-lookup", version: "2.0.0", changelog: "输出结构升级", publishedAt: "2026-07-05T00:00:00.000Z" },
  { skillId: "skill-wiki-search", version: "1.0.0", changelog: "初始版本", publishedAt: "2026-07-01T00:00:00.000Z" },
];

export const skillBindings = [
  { id: "bind-ecs-ticket", agentId: "ecs-assistant", skillId: "skill-ticket-lookup", boundBy: "pm-chen", boundAt: "2026-07-06T00:00:00.000Z" },
];

export const releases = [
  {
    id: "rel-000",
    agentId: "ecs-assistant",
    changeNote: "初始发布",
    changedPartitions: ["PROMPT", "KNOWLEDGE", "TOOLS", "ROUTING"],
    status: "APPROVED",
    submittedBy: "system",
    submittedAt: "2026-06-15T08:00:00.000Z",
    approvedBy: "admin-zhao",
    approvedAt: "2026-06-15T08:00:00.000Z",
    reviewComment: "初始版本上线",
    configSnapshot: null,
    version: null,
  },
  {
    id: "rel-001",
    agentId: "ecs-assistant",
    changeNote: "根据反馈优化安全组相关知识，补充方向性说明",
    changedPartitions: ["KNOWLEDGE"],
    status: "APPROVED",
    submittedBy: "pm-chen",
    submittedAt: "2026-07-13T10:00:00.000Z",
    approvedBy: "admin-zhao",
    approvedAt: "2026-07-13T14:00:00.000Z",
    reviewComment: "知识补充完整，可以发布",
    configSnapshot: null,
    version: { id: "ver-002", version: "0.2.0", publishedAt: "2026-07-13T14:00:00.000Z" },
  },
  {
    id: "rel-002",
    agentId: "ecs-assistant",
    changeNote: "补充高危操作风险提示，磁盘扩容前需提醒创建快照",
    changedPartitions: ["PROMPT", "ROUTING"],
    status: "PENDING",
    submittedBy: "pm-chen",
    submittedAt: "2026-07-14T09:00:00.000Z",
    approvedBy: null,
    approvedAt: null,
    reviewComment: null,
    configSnapshot: null,
    version: null,
  },
  {
    id: "rel-rds-000",
    agentId: "rds-assistant",
    changeNote: "初始发布",
    changedPartitions: ["PROMPT", "KNOWLEDGE", "TOOLS", "ROUTING"],
    status: "APPROVED",
    submittedBy: "system",
    submittedAt: "2026-06-20T10:00:00.000Z",
    approvedBy: "admin-zhao",
    approvedAt: "2026-06-20T10:00:00.000Z",
    reviewComment: "初始版本上线",
    configSnapshot: null,
    version: null,
  },
];

export const versions = [
  {
    id: "ver-001",
    agentId: "ecs-assistant",
    version: "0.1.0",
    major: 0,
    minor: 1,
    patch: 0,
    promptSnapshot: {
      systemPrompt: "你是一个专业的 ECS 云服务器技术支持助手。你的职责是帮助 CRE（客户可靠性工程师）快速定位和解决 ECS 相关工单问题。\n\n## 核心能力\n- ECS 实例管理（创建、启停、释放、变配）\n- 网络配置（VPC、安全组、弹性公网 IP）\n- 存储管理（云盘、快照、NAS 挂载）\n- 故障排查（实例无法连接、性能问题、系统异常）\n\n## 回答原则\n1. 先确认问题现象和环境信息\n2. 给出排查步骤和可能的解决方案\n3. 涉及高危操作时明确提示风险\n4. 不确定的问题建议联系 ECS 内核团队",
      roleDefinition: "ECS 技术支持专家",
      constraints: ["不回答非 ECS 产品的问题", "不执行任何实际变更操作", "涉及数据安全的问题提醒用户注意"],
      outputFormat: "Markdown",
    },
    knowledgeSnapshot: {
      wikiVaultId: "ecs-wiki",
      searchStrategy: "WIKI_FIRST",
      fallbackToMcp: true,
      maxWikiResults: 3,
      confidenceThreshold: 0.5,
    },
    toolsSnapshot: {
      mcpTools: [
        {
          name: "ecs_instance_query",
          displayName: "ECS 实例查询",
          description: "根据实例 ID 或条件查询 ECS 实例状态",
          endpoint: "https://ecs-api.internal/v1/instances",
          method: "GET",
          inputSchema: { type: "object", properties: { instanceId: { type: "string" } } },
          outputSchema: { type: "object" },
          authType: "bearer",
          permissionScope: "read_only",
          enabled: true,
        },
      ],
      wikiQueryTools: [
        {
          name: "wiki_search",
          displayName: "知识库搜索",
          description: "在 ECS 知识库中搜索相关知识",
          searchType: "hybrid",
          maxResults: 5,
          minConfidence: 0.6,
          enabled: true,
        },
      ],
      maxConcurrentCalls: 3,
      timeoutMs: 30000,
      retryCount: 2,
    },
    routingSnapshot: {
      rules: [
        {
          id: "rule-1",
          name: "实例无法连接",
          matchCondition: { keywords: ["无法连接", "SSH失败", "远程桌面", "网络不通"], category: "connectivity" },
          action: { type: "route_to_agent", targetAgentId: "ecs-assistant", priority: 1 },
        },
        {
          id: "rule-2",
          name: "性能问题",
          matchCondition: { keywords: ["CPU高", "内存不足", "磁盘满", "IO瓶颈"], category: "performance" },
          action: { type: "route_to_agent", targetAgentId: "ecs-assistant", priority: 2 },
        },
      ],
      defaultAction: { type: "route_to_human", reason: "未匹配到已知问题类型" },
      humanThreshold: 0.3,
      maxConversationTurns: 10,
      idleTimeoutMinutes: 5,
    },
    releaseId: "rel-000",
    publishedBy: "admin-zhao",
    publishedAt: "2026-06-15T08:00:00.000Z",
    changeNote: "初始发布",
    effectivenessReport: {
      totalFeedbacks: 0,
      byRating: { POSITIVE: 0, NEGATIVE: 0, NEUTRAL: 0 },
      bySeverity: { CRITICAL: 0, MAJOR: 0, MINOR: 0, SUGGESTION: 0 },
      byPartition: { PROMPT: 0, KNOWLEDGE: 0, TOOLS: 0, ROUTING: 0 },
      computedAt: "2026-08-05T04:15:59.941Z",
      versionPublishedAt: "2026-06-15T08:00:00.000Z",
      windowDays: 7,
    },
  },
  {
    id: "ver-002",
    agentId: "ecs-assistant",
    version: "0.2.0",
    major: 0,
    minor: 2,
    patch: 0,
    promptSnapshot: {
      systemPrompt: "你是一个专业的 ECS 云服务器技术支持助手。你的职责是帮助 CRE（客户可靠性工程师）快速定位和解决 ECS 相关工单问题。\n\n## 核心能力\n- ECS 实例管理（创建、启停、释放、变配）\n- 网络配置（VPC、安全组、弹性公网 IP）\n- 存储管理（云盘、快照、NAS 挂载）\n- 故障排查（实例无法连接、性能问题、系统异常）\n\n## 回答原则\n1. 先确认问题现象和环境信息\n2. 给出排查步骤和可能的解决方案\n3. 涉及高危操作时明确提示风险\n4. 不确定的问题建议联系 ECS 内核团队",
      roleDefinition: "ECS 技术支持专家",
      constraints: ["不回答非 ECS 产品的问题", "不执行任何实际变更操作", "涉及数据安全的问题提醒用户注意"],
      outputFormat: "Markdown",
    },
    knowledgeSnapshot: {
      wikiVaultId: "ecs-wiki",
      searchStrategy: "WIKI_FIRST",
      fallbackToMcp: true,
      maxWikiResults: 5,
      confidenceThreshold: 0.6,
    },
    toolsSnapshot: {
      mcpTools: [
        {
          name: "ecs_instance_query",
          displayName: "ECS 实例查询",
          description: "根据实例 ID 或条件查询 ECS 实例状态",
          endpoint: "https://ecs-api.internal/v1/instances",
          method: "GET",
          inputSchema: { type: "object", properties: { instanceId: { type: "string" } } },
          outputSchema: { type: "object" },
          authType: "bearer",
          permissionScope: "read_only",
          enabled: true,
        },
      ],
      wikiQueryTools: [
        {
          name: "wiki_search",
          displayName: "知识库搜索",
          description: "在 ECS 知识库中搜索相关知识",
          searchType: "hybrid",
          maxResults: 5,
          minConfidence: 0.6,
          enabled: true,
        },
      ],
      maxConcurrentCalls: 3,
      timeoutMs: 30000,
      retryCount: 2,
    },
    routingSnapshot: {
      rules: [
        {
          id: "rule-1",
          name: "实例无法连接",
          matchCondition: { keywords: ["无法连接", "SSH失败", "远程桌面", "网络不通"], category: "connectivity" },
          action: { type: "route_to_agent", targetAgentId: "ecs-assistant", priority: 1 },
        },
        {
          id: "rule-2",
          name: "性能问题",
          matchCondition: { keywords: ["CPU高", "内存不足", "磁盘满", "IO瓶颈"], category: "performance" },
          action: { type: "route_to_agent", targetAgentId: "ecs-assistant", priority: 2 },
        },
      ],
      defaultAction: { type: "route_to_human", reason: "未匹配到已知问题类型" },
      humanThreshold: 0.3,
      maxConversationTurns: 10,
      idleTimeoutMinutes: 5,
    },
    releaseId: "rel-001",
    publishedBy: "admin-zhao",
    publishedAt: "2026-07-13T14:00:00.000Z",
    changeNote: "根据反馈优化安全组相关知识，补充方向性说明",
    effectivenessReport: {
      totalFeedbacks: 0,
      byRating: { POSITIVE: 0, NEGATIVE: 0, NEUTRAL: 0 },
      bySeverity: { CRITICAL: 0, MAJOR: 0, MINOR: 0, SUGGESTION: 0 },
      byPartition: { PROMPT: 0, KNOWLEDGE: 0, TOOLS: 0, ROUTING: 0 },
      computedAt: "2026-08-05T04:15:59.938Z",
      versionPublishedAt: "2026-07-13T14:00:00.000Z",
      windowDays: 7,
    },
  },
  {
    id: "ver-rds-001",
    agentId: "rds-assistant",
    version: "0.1.0",
    major: 0,
    minor: 1,
    patch: 0,
    promptSnapshot: {
      systemPrompt: "你是一个专业的 RDS 数据库技术支持助手。帮助 CRE 处理 MySQL、PostgreSQL、SQL Server 等数据库相关工单。\n\n## 核心能力\n- 数据库连接问题排查\n- 慢查询分析与优化建议\n- 备份恢复操作指导\n- 参数调优建议",
      roleDefinition: "RDS 数据库技术支持专家",
      constraints: ["不执行 DDL/DML 操作", "涉及数据迁移时提醒备份", "不直接查看用户数据"],
      outputFormat: "Markdown",
    },
    knowledgeSnapshot: {
      wikiVaultId: "rds-wiki",
      searchStrategy: "WIKI_FIRST",
      fallbackToMcp: true,
      maxWikiResults: 5,
      confidenceThreshold: 0.6,
    },
    toolsSnapshot: {
      mcpTools: [],
      wikiQueryTools: [],
      maxConcurrentCalls: 3,
      timeoutMs: 30000,
      retryCount: 2,
    },
    routingSnapshot: {
      rules: [],
      defaultAction: { type: "route_to_human", reason: "未匹配已知问题" },
      humanThreshold: 0.3,
      maxConversationTurns: 10,
      idleTimeoutMinutes: 5,
    },
    releaseId: "rel-rds-000",
    publishedBy: "admin-zhao",
    publishedAt: "2026-06-20T10:00:00.000Z",
    changeNote: "初始发布",
  },
];

export const feedback = [
  {
    id: "fb-001",
    agentId: "ecs-assistant",
    source: "MANUAL",
    title: "安全组规则说明不够清晰",
    content: "用户询问如何配置安全组放通特定端口时，Agent 给出了正确的操作步骤，但对'方向'（入方向/出方向）的解释不够清晰，导致用户反复确认。建议补充安全组方向性的解释说明。",
    rating: "NEGATIVE",
    tags: ["ANSWER_QUALITY", "KNOWLEDGE_GAP"],
    severity: "MINOR",
    status: "NEW",
    targetPartition: "KNOWLEDGE",
    submittedBy: "cre-zhang",
    submittedAt: "2026-07-12T09:30:00.000Z",
  },
  {
    id: "fb-002",
    agentId: "ecs-assistant",
    source: "MANUAL",
    title: "误判磁盘扩容操作风险等级",
    content: "用户询问在线扩容云盘时，Agent 将扩容操作标记为'低风险'，但实际在线扩容存在一定数据风险，应提醒用户先创建快照。Agent 对高危操作的风险提示不足。",
    rating: "NEGATIVE",
    tags: ["ANSWER_QUALITY", "OUTDATED_INFO"],
    severity: "MAJOR",
    status: "TRIAGED",
    targetPartition: "PROMPT",
    submittedBy: "cre-li",
    submittedAt: "2026-07-11T15:20:00.000Z",
  },
  {
    id: "fb-003",
    agentId: "ecs-assistant",
    source: "MANUAL",
    title: "SSH 连接排查流程很完善",
    content: "用户反馈 SSH 连接失败的排查流程非常完整，从网络连通性到密钥验证到端口检查都覆盖了，一次就解决了问题。",
    rating: "POSITIVE",
    tags: ["ANSWER_QUALITY"],
    severity: "SUGGESTION",
    status: "VERIFIED",
    submittedBy: "cre-wang",
    submittedAt: "2026-07-10T11:00:00.000Z",
  },
];

export const evalCases = [
  {
    id: "eval-ecs-001",
    agentId: "ecs-assistant",
    sourceTraceId: "trace-ecs-001",
    title: "ECS 实例无法 SSH 连接，怎么排查？",
    expectation: "先确认现象与环境信息，再按「网络连通 → 安全组 → 密钥/服务」顺序给出排查步骤，涉及高危操作（如重启）前明确提示风险",
    systemPrompt: "你是一个专业的 ECS 云服务器技术支持助手。你的职责是帮助 CRE（客户可靠性工程师）快速定位和解决 ECS 相关工单问题。",
    history: [],
    message: "我们有一台 ECS 实例突然 SSH 连不上了，ping 也不通，之前一直正常。可能是哪些原因？",
    referenceReply: "SSH 连不上且 ping 不通，建议按下面顺序排查：\n\n1. **先确认状态与视图**：登录控制台确认实例处于「运行中」（欠费/停机都会导致无法连接），并查看实例监控里的公网流量，判断是「网络不通」还是「只是 SSH 不通」。\n2. **网络连通性**：ping 不通通常是安全组或网络路径问题——检查安全组入方向是否放行了 ICMP 与 22 端口，来源 IP 是否限制过窄（比如只允许了已变化的办公室出口 IP）。\n3. **系统层面**：如果控制台 VNC 能登录，用 `systemctl status sshd` 检查 sshd 是否在运行、`ss -lntp | grep :22` 确认监听；再确认本地是否换了密钥对/密码过期。\n4. **兜底手段**：上述都无法定位时，可通过控制台「远程连接」进入实例排查，必要时联系 ECS 内核团队。\n\n⚠️ 提醒：如果最后需要重启实例才能恢复，重启会造成秒级中断，建议先确认没有正在运行的关键任务。",
    assertions: [
      { type: "contains", value: "安全组", description: "回复必须覆盖安全组方向的网络排查" },
      { type: "contains", value: "systemctl", description: "回复必须给出检查 sshd 服务状态的具体命令" },
    ],
    status: "ACTIVE",
    createdAt: "2026-07-15T09:30:00.000Z",
    createdBy: "eng-li",
  },
  {
    id: "eval-ecs-002",
    agentId: "ecs-assistant",
    sourceTraceId: "trace-ecs-002",
    title: "磁盘扩容后容量没变化",
    expectation: "必须提醒：扩容前先创建快照备份；扩容后若容量未变化，需在操作系统内完成分区/文件系统扩展（growpart + resize2fs），并解释控制台扩容 ≠ 系统内生效",
    systemPrompt: "你是一个专业的 ECS 云服务器技术支持专家。涉及数据安全的问题必须提醒用户注意。",
    history: [],
    message: "我在控制台给数据盘扩容了 50G，但服务器里 df -h 还是显示原来的大小，容量没变化，怎么办？",
    referenceReply: "控制台扩容只是把「云盘容量上限」扩大，操作系统里还看不到，这是正常现象，还需要在系统内完成最后一步。按下面操作：\n\n1. **扩容前先创建快照**：磁盘操作有风险，建议先在控制台为这块云盘创建一份快照，出问题可随时回滚。（如果还没扩容，请先做快照再继续。）\n2. **确认盘符与扩容结果**：`lsblk` 查看云盘实际容量是否已变为新大小。\n3. **扩展分区**：`growpart /dev/vdb 1`（以数据盘 vdb 为例）把分区表扩展到新容量。\n4. **扩展文件系统**：ext4 执行 `resize2fs /dev/vdb1`，xfs 执行 `xfs_growfs /mount-point`，然后 `df -h` 验证容量。\n\n⚠️ 注意：扩容和文件系统调整属于高风险操作，操作前务必确认快照已创建；如果分区里有数据库等关键服务，建议在业务低峰期操作并提前联系相关团队。",
    assertions: [
      { type: "regex", value: "快照", description: "回复必须提醒先创建快照备份（磁盘操作高危）" },
    ],
    status: "ACTIVE",
    createdAt: "2026-07-15T11:20:00.000Z",
    createdBy: "eng-li",
  },
];

export const auditLogs = [
  {
    id: "log-001",
    action: "agent.update",
    resource: "agent",
    resourceId: "ecs-assistant",
    userName: "pm-chen",
    userRole: "product_member",
    createdAt: "2026-07-14T09:00:00.000Z",
    details: { partition: "PROMPT", changeNote: "补充高危操作风险提示" },
  },
  {
    id: "log-002",
    action: "release.submit",
    resource: "release",
    resourceId: "rel-002",
    userName: "pm-chen",
    userRole: "product_member",
    createdAt: "2026-07-14T09:00:00.000Z",
    details: { agentId: "ecs-assistant" },
  },
  {
    id: "log-003",
    action: "release.approve",
    resource: "release",
    resourceId: "rel-001",
    userName: "admin-zhao",
    userRole: "platform_admin",
    createdAt: "2026-07-13T14:00:00.000Z",
    details: { agentId: "ecs-assistant" },
  },
  {
    id: "log-004",
    action: "feedback.create",
    resource: "feedback",
    resourceId: "fb-003",
    userName: "cre-wang",
    userRole: "cre_viewer",
    createdAt: "2026-07-10T11:00:00.000Z",
    details: { agentId: "ecs-assistant", rating: "POSITIVE" },
  },
  {
    id: "log-005",
    action: "wiki.page.update",
    resource: "wiki-page",
    resourceId: "page-ecs-sg",
    userName: "pm-chen",
    userRole: "product_member",
    createdAt: "2026-07-13T13:30:00.000Z",
    details: { vaultId: "ecs-wiki", title: "安全组配置指南" },
  },
];

export const seedData = {
  users,
  permissions,
  roles,
  productGroups,
  productGroupMembers,
  userRoles,
  agents,
  wikiVaults,
  wikiPages,
  skills,
  skillVersions,
  skillBindings,
  releases,
  versions,
  feedback,
  evalCases,
  auditLogs,
};

export default seedData;
